[project]
name = "zarr-sqlite"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Francis Thérien", email = "frtherien@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "zarr>=3.1.0",
]

[project.optional-dependencies]
test = [
    "mypy>=1.17.0",
    "pytest>=8.4.1",
]

[build-system]
requires = ["uv_build>=0.8.3,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "numpy>=2.3.2",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
markers = [
    "asyncio: mark a test as an asyncio coroutine",
]
